# Generated by Django 4.1.7 on 2023-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('F', 'FULL TIME'), ('P', 'PART TIME'), ('C', 'CONTRACT')], default='F', max_length=2),
        ),
    ]
