# Generated by Django 4.1.7 on 2023-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobpost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('FULL TIME', 'full_time'), ('PART TIME', 'part_time'), ('CONTRACT', 'contract')], default='full_time', max_length=50),
        ),
    ]
