# Generated by Django 4.1.7 on 2023-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribs',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscribs',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
